site_name: unobin standard library
site_url: https://cloudboss.co/docs/unobin-library-std/
repo_url: https://github.com/cloudboss/unobin-library-std
repo_name: cloudboss/unobin-library-std
copyright: Copyright (c) 2026 cloudboss

theme:
  name: cloudboss
  logo: assets/logo.svg
  favicon: assets/logo.svg

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md

extra:
  google_analytics_property: G-MZGMN4NWS2
  unobin_reference: true
  version:
    provider: mike
    default: latest

nav:
  - Standard library: index.md
  - Reference:
      - Overview: reference/index.md
      - Resources: reference/resources/
      - Actions: reference/actions/
